TRAINING_DATA_DIR = "D:/ai_gaming/data/"
TRAINING_BATCH = "D:/ai_gaming/data/train_split/training_data{}.npy"
TRAINING_DATA_PATH = "D:/ai_gaming/data/training_data.npy"
TESTING_DATA_PATH = "D:/ai_gaming/data/testing_data.npy"
CSV_BATCH_RECORD = "D:/ai_gaming/data/files.csv"
FINAL_TRAINING_DATA = "D:/ai_gaming/data/final_training_data.npy"
MODEL_DIR = "D:/ai_gaming/model"
BIKE_TRAINING_DATA_PATH = "D:/ai_gaming/data/bike_data_balanced/training_data"
